---

# tasks file for haproxy-pg
- name: set distro independed variables
  ansible.builtin.include_vars:
    file: "{{ haproxy_vars_dir }}/main.yml"
  tags: haproxy,haproxy_install,haproxy_cfg

- name: install haproxy package(s) if needed
  ansible.builtin.package:
    name: "{{ haproxy_apt_packages }}"
    state: present
  register: haproxy_install_result
  tags: haproxy,haproxy_install

- name: check if exists haproxy.cfg.install
  ansible.builtin.stat:
    path: "{{ haproxy_cfg_file }}.install"
  register: haproxy_cfg_install
  tags: haproxy,haproxy_cfg

- name: create backup of installed config 
  ansible.builtin.copy:
    src: "{{ haproxy_cfg_file }}"
    dest: "{{ haproxy_cfg_file }}.install"
    remote_src: true
  when: not haproxy_cfg_install.stat.exists and haproxy_install_result.changed
  tags: haproxy,haproxy_cfg

- name: configure haproxy for pg
  ansible.builtin.template:
    src: "{{ haproxy_templates_dir }}/haproxy-pg.cfg.j2"
    dest: "{{ haproxy_cfg_file }}"
    owner: '{{ haproxy_user }}'
    group: '{{ haproxy_group }}'
  notify: haproxy restart
  tags: haproxy,haproxy_cfg
