---
# handlers file for haproxy-pg
- name: Haproxy enable
  ansible.builtin.service:
    name: haproxy
    enabled: true

- name: Haproxy start
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Haproxy stop
  ansible.builtin.service:
    name: haproxy
    state: stopped

- name: Haproxy restart
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Haproxy reload
  ansible.builtin.service:
    name: haproxy
    state: reloaded

- name: Haproxy disable
  ansible.builtin.service:
    name: haproxy
    enabled: false
